[workspace]
members = ["ctru-rs", "ctru-sys"]

[patch.'https://github.com/Meziu/libc']
libc = "0.2.123"

[patch.'https://github.com/Meziu/ctru-rs']
# Make sure all dependencies use the local ctru-sys package
ctru-sys = { path = "ctru-sys" }